const CONTACT_EMAIL = "matt@bamboo.holdings";
const TODAY = "June 8, 2026";

const apps = [
  {
    id: "chalk",
    name: "Chalk",
    slug: "/apps/chalk/",
    icon: "/assets/apps/chalk-icon.png",
    status: "TestFlight",
    tagline: "The gymnastics coaching companion",
    hero: "Every session. Every skill. Every athlete.",
    intro: "Chalk helps gymnastics coaches log sessions, rate skills, and send personalized drill plans to athletes and parents.",
    long: "Chalk brings the daily coaching workflow into one place. Coaches can log individual or class sessions, rate athlete skills on a simple 1-4 scale, and review personalized homework plans generated from those session ratings.",
    users: ["Gymnastics coaches", "Youth gymnasts and athletes", "Parents who want safe visibility into homework and progress", "Gym owners, program directors, and facility admins"],
    features: [["Rate, plan, send", "Log a session, rate skills, and turn practice notes into a focused homework plan."], ["Built for class flow", "Move through activity areas, collect ratings for the whole class, and review everything before closing the session."], ["Homework that fits", "Plans are generated from the day's ratings, with flexibility built in and a focused cap."], ["Four views, one workflow", "Coaches, athletes, parents, and admins each see the information they need."], ["Track the journey", "Skill trees, milestones, session history, and progress comparisons help make improvement visible."], ["Private by design", "No accounts, no ads, and no server sync in the current preview. Data is stored on the device."]],
    works: ["Choose a role: Coach, Athlete, Parent, or Admin.", "Log an individual athlete session or start a class session.", "Rate skills and add notes.", "Review the homework draft.", "Send homework to the athlete and parent views.", "Track progress over time."],
    availability: "Currently in TestFlight for iOS.",
    disclaimer: "Chalk is a preview product for youth sports workflows. Public privacy and compliance details should receive owner and legal review before launch.",
    support: {
      overview: "Chalk is a gymnastics coaching companion for session logging, skill tracking, and homework follow-through. The current preview uses local on-device data and does not include accounts or cloud sync.",
      include: ["Your iPhone model", "Your iOS version", "Chalk app version if visible", "Whether you are using demo data or custom data", "A short description of the issue"],
      faq: [["How do I log a training session?", "Open the Coach view, choose an athlete or class, rate the relevant skills, add notes if needed, and save the session."], ["What do the 1-4 ratings mean?", "1 means Needs Work, 2 means Developing, 3 means Almost There, and 4 means Nailed It."], ["How does homework get created?", "After a session, Chalk creates a homework draft from the ratings. Coaches can review and adjust the plan before sending it."], ["Does Chalk require a login?", "No. The current preview has no account system. It opens to a role picker."], ["Will data sync to another device?", "No. Current data is stored on the device only and does not sync across devices."]],
      limitations: ["iOS TestFlight only currently", "No account system", "No cloud backup or multi-device sync", "No Android build currently", "No push notifications currently", "No AI processing or machine learning in the homework engine", "Data can be lost if the app is deleted or the device is replaced without backup"]
    },
    privacy: {
      stored: ["Athlete names and ages", "Coach names and roster information", "Parent display information in demo or facility data", "Session ratings and notes", "Homework plans and completion records", "Practice logs", "Skill progress and milestone records", "Custom skills and drills", "Facility name, tagline, and location text", "Class, program, roster, and curriculum configuration", "Optional skill video URLs"],
      local: "Current Chalk preview data is stored locally on the user's device. Chalk does not currently operate a user account system, backend database, or server sync for product data.",
      thirdParty: "No third-party AI, analytics, advertising, tracking, or crash-reporting services are used in the current preview. Optional video links may be entered as skill references, but Chalk does not upload user training data to those services.",
      accounts: "Chalk currently has no account system, login flow, Apple Sign In, Google Sign In, or remote profile.",
      ai: "Chalk does not use AI or external model providers for homework generation. Homework is generated by local rule-based logic.",
      children: "Chalk may be used to store information about youth athletes, including names, ages, skill notes, and training records. This section should receive legal review before public launch.",
      payments: "Chalk currently has no subscriptions, in-app purchases, or payment processing.",
      tracking: "Chalk currently does not use analytics SDKs, advertising identifiers, behavioral tracking, or third-party crash reporting.",
      deletion: "Users can reset demo data from Admin settings. App deletion also removes locally stored app data, subject to device backup behavior. There is currently no cloud account to delete."
    }
  },
  {
    id: "triptracker-pro",
    name: "TripTracker Pro",
    slug: "/apps/triptracker-pro/",
    icon: "/assets/apps/triptracker-pro-icon.png",
    status: "Available on iOS",
    appStoreUrl: "https://apps.apple.com/us/app/triptracker-pro/id6762306487",
    tagline: "AI-powered resort receipt tracking",
    hero: "Every charge, every tip, every receipt - accounted for.",
    intro: "TripTracker Pro helps resort travelers scan receipts, track expenses, reconcile hotel bills, split costs, and keep a clean record of their trip.",
    long: "TripTracker Pro turns the financial chaos of a resort vacation into a clear, organized record. Travelers can photograph receipts, review AI-extracted line items, compare saved receipts against a hotel folio, track shared expenses, and keep notes about resorts and staff.",
    users: ["Frequent resort and timeshare travelers", "Travelers managing multi-person trips", "People who want to reconcile hotel folios before checkout", "Travelers who track cash tips, card charges, and shared expenses", "Resort guests who want notes and records to carry forward to future stays"],
    features: [["Scan receipts as you go", "Capture receipts during the trip and review extracted details before saving."], ["Reconcile your hotel bill", "Compare your final folio against saved receipts and spot charges that need review."], ["Split costs without a spreadsheet", "Track shared expenses and see a clean settlement summary at the end of the trip."], ["Remember staff and tips", "Keep a record of staff names, roles, and tip history across resort visits."], ["Keep resort notes", "Save details about a property so they are available next time you return."], ["Export your trip record", "Create a portable trip file for personal records or device migration."]],
    works: ["Create a trip with resort, dates, currencies, and optional budget.", "Scan receipts throughout the stay.", "Upload the hotel folio near checkout.", "Review matched and disputed charges.", "Settle shared expenses.", "Export a clean trip summary."],
    availability: "Available now on the iOS App Store. Android coming soon.",
    disclaimer: "TripTracker Pro is a personal record-keeping tool. AI extraction may be incomplete or incorrect, and users should review receipts, folios, and exports carefully.",
    support: {
      overview: "TripTracker Pro is a personal travel expense tracker for resort trips. Most issues can be fixed directly in the app by editing receipts, updating trip settings, or exporting/importing trip data.",
      include: ["Device model", "iOS or Android version", "TripTracker Pro version if visible in Settings", "A short description of the issue", "Screenshots if helpful"],
      faq: [["How do I scan a receipt?", "Open the receipt scanning flow, take a clear photo, review the extracted fields, correct anything that looks wrong, and save."], ["Can I fix an AI extraction mistake?", "Yes. Open the receipt and edit the incorrect fields manually."], ["How does folio reconciliation work?", "Upload a hotel folio or final bill. TripTracker Pro compares the folio line items against saved receipts and expenses."], ["Does TripTracker Pro sync across devices?", "No. Current trip data is stored locally on the device. Export/import is the current way to move data."], ["Does the app work offline?", "Many tracking features can work without internet. AI-powered scanning, folio extraction, assistant features, and weather-related features require internet access."]],
      limitations: ["No cross-device sync currently", "No account recovery because there is no account system", "AI extraction depends on image quality and receipt format", "Exchange rates are user-configured and may not match actual transaction rates", "Manual export/import is required to move records between devices"]
    },
    privacy: {
      stored: ["Trip names, dates, resort details, room details, and traveler names", "Receipt amounts, item names, tips, totals, and currencies", "Receipt photos and hotel folio photos", "Cash expenses and shared ledger entries", "Staff names, staff roles, and tip history", "Flight details and confirmation information", "Resort notes and saved places", "App preferences", "AI assistant messages and uploaded context"],
      local: "Trip records, receipts, expenses, ledger entries, notes, people records, and preferences are stored on the user's device. Receipt and folio images may be stored in the device file system.",
      thirdParty: "AI-powered features may transmit relevant content to a third-party AI provider for processing. This can include receipt images, folio images, flight confirmation images, extracted text, or assistant messages. Weather-related features may use a weather or geocoding service based on resort location information.",
      accounts: "TripTracker Pro currently does not require a user account or sign-in.",
      ai: "Receipt, folio, flight, and assistant features may use external AI processing. AI results should be reviewed and corrected when needed.",
      children: "TripTracker Pro is not intended for children under 13.",
      payments: "TripTracker Pro is available through the iOS App Store. This page does not make separate claims about pricing, subscriptions, or in-app purchases.",
      tracking: "No analytics, advertising, or tracking claims are made unless confirmed against the current codebase before publication.",
      deletion: "Users can delete app records from within the app. Exact full-data-reset behavior should be confirmed before publishing detailed instructions."
    }
  },
  {
    id: "match-card",
    name: "Match Card",
    slug: "/apps/match-card/",
    icon: "/assets/apps/match-card-icon.png",
    status: "Available on iOS",
    appStoreUrl: "https://apps.apple.com/us/app/match-card-pro/id6762983683",
    tagline: "Golf scorecard and round analytics",
    hero: "Your courses. Your rivalry. One scorecard.",
    intro: "Match Card is a two-player golf scorecard for iPhone that helps regular playing partners score rounds, track rivalry stats, settle friendly side games, and keep a course-by-course record.",
    long: "Match Card is built for golfers who play the same courses with the same regular partner and care about the rivalry as much as the score. It keeps live scoring simple, supports tap or voice score entry, tracks per-course performance, calculates a course-specific handicap, and keeps a season-long head-to-head trophy.",
    users: ["Recreational golfers who play regularly with the same partner", "Two-player golf rivalries", "Golfers who care about course-specific history and head-to-head records", "Players who want a cleaner alternative to bloated golf apps", "Golfers who want side-game math handled for them"],
    features: [["Live scoring, one-handed", "Fast hole-by-hole scoring with auto-saving drafts."], ["Score with your voice", "Tap the mic, say the scores, and keep the round moving."], ["Built for rivalries", "Track the season-long head-to-head between you and your regular playing partner."], ["Per-course handicap", "Keep course-specific performance history instead of one blended number."], ["Side games settled", "Handle Skins, Match Play, Nassau, Stableford, and more without spreadsheet math."], ["Share the round", "Generate clean post-round share cards for scores, stats, and highlights."]],
    works: ["Set your two player names.", "Choose or add a course.", "Score each hole by tap or voice.", "Save the round.", "Review side games and the season trophy.", "Share the result if you want."],
    availability: "Available now on the iOS App Store. Android coming soon.",
    disclaimer: "Match Card can tally friendly side games, but it does not process payments, transfer money, or settle wagers.",
    support: {
      overview: "Match Card is a two-player golf scorecard for iPhone. It does not require an account and is designed to work offline for round scoring.",
      include: ["iPhone model", "iOS version", "Match Card app version if visible", "A short description of the issue", "What screen you were on"],
      faq: [["Do I need an account?", "No. Match Card does not require sign-in or account creation."], ["How does voice scoring work?", "Tap the microphone on the live scoring screen and say the scores. It is a tap-to-record feature, not always-listening."], ["Why does the app ask for location?", "Location may be used to capture a weather stamp for the round or bias course search. If location is denied, the app should still support scoring."], ["Is my data backed up?", "Only if the user enables optional backup. Backup is off by default."], ["Does Match Card handle money or betting payments?", "No. Match Card can tally friendly side games, but it does not process payments, transfer money, or settle wagers."]],
      limitations: ["iOS only currently", "Android coming soon", "No live multi-device sync", "Optional backup is not an account system", "No always-listening voice mode"]
    },
    privacy: {
      stored: ["Round scores and scoring details", "Player names", "Course and venue records", "Hole notes and course history", "Bag and club data", "Side-game results", "App settings", "Attached local photo references", "Derived stats, records, and handicap calculations"],
      local: "Match Card is local-first and account-free. Most scoring, stats, handicap, course, and settings data lives on the user's device.",
      thirdParty: "Depending on which features the user chooses, Match Card may send limited data to service providers, including voice clips for transcription, scorecard images for parsing, course search queries, approximate location for course lookup, and approximate coordinates for weather information.",
      accounts: "Match Card currently does not require user accounts, login, email, Apple Sign In, or Google Sign In.",
      ai: "Voice, image, location, and course-search processing are feature-specific and should not be described as advertising or tracking.",
      children: "Match Card is not directed at children.",
      payments: "Match Card is available through the iOS App Store. Match Card does not process payments, transfer money, or settle wagers.",
      tracking: "No analytics, advertising, or tracking claims are made unless confirmed against the current codebase before publication.",
      deletion: "Users can erase local data in the app. Optional backup, if enabled, should be deleted separately through the backup feature."
    }
  }
];

const nav = [
  ["Home", "#top"],
  ["Bio", "#bio"],
  ["Apps", "#apps"],
  ["Contact", "#contact"]
];

const siteRootUrl = new URL(".", document.currentScript ? document.currentScript.src : window.location.href);
const isFilePreview = window.location.protocol === "file:";

function assetUrl(path) {
  if (/^(mailto:|https?:|file:|#)/.test(path)) return path;
  if (!isFilePreview) return path;
  return new URL(path.replace(/^\//, ""), siteRootUrl).href;
}

function pageUrl(path) {
  if (/^(mailto:|https?:|file:|#)/.test(path)) return path;
  if (!isFilePreview) return path;
  const clean = path.replace(/^\//, "");
  if (!clean) return new URL("index.html", siteRootUrl).href;
  if (clean.endsWith("/")) return new URL(`${clean}index.html`, siteRootUrl).href;
  return new URL(clean, siteRootUrl).href;
}

function esc(value) {
  return String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
}

function list(items) {
  return `<ul class="list">${items.map(item => `<li>${esc(item)}</li>`).join("")}</ul>`;
}

function cards(items) {
  return `<div class="grid">${items.map(([title, body]) => `<article class="card"><h3>${esc(title)}</h3><p>${esc(body)}</p></article>`).join("")}</div>`;
}

function appIcon(app) {
  const initials = esc(app.name.split(" ").map(word => word[0]).join("").slice(0, 2));
  if (app.icon) {
    return `<div class="app-icon has-image"><img src="${esc(assetUrl(app.icon))}" alt="${esc(app.name)} icon" onerror="this.parentElement.classList.remove('has-image'); this.replaceWith(document.createTextNode('${initials}'))"></div>`;
  }
  return `<div class="app-icon" aria-hidden="true">${initials}</div>`;
}

function appStoreBadge(url) {
  return `<a class="app-store-badge" href="${esc(url)}" aria-label="Download on the App Store">
    <img src="${assetUrl("/assets/brand/download-on-app-store.svg")}" alt="Download on the App Store">
  </a>`;
}

function shell(title, active, content) {
  document.title = title;
  document.body.className = active === "Home" ? "home-page" : "";
  document.body.innerHTML = `
    <a class="skip-link" href="#main">Skip to content</a>
    <div class="ambient-frame" aria-hidden="true"><span></span><span></span><span></span></div>
    <header class="site-header">
      <div class="inner">
        <nav class="nav" aria-label="Primary">
          <a class="brand" href="${pageUrl("/")}">
            <img src="${assetUrl("/assets/brand/bamboo-holdings-logo-hq.png")}" alt="" onerror="this.src='${assetUrl("/assets/brand/bamboo-logo.png")}'; this.onerror=()=>this.replaceWith(Object.assign(document.createElement('span'), {className: 'brand-mark', textContent: 'B'}))">
            <span>Bamboo Holdings</span>
          </a>
          <div class="nav-links">${nav.map(([label, href]) => `<a href="${pageUrl(href)}"${label === active ? ' aria-current="page"' : ""}>${label}</a>`).join("")}</div>
        </nav>
      </div>
    </header>
    <main id="main">${content}</main>
    <footer class="site-footer">
      <div class="inner footer-grid">
        <span>&copy; ${new Date().getFullYear()} Bamboo Holdings.</span>
        <div class="footer-links">${nav.map(([label, href]) => `<a href="${pageUrl(href)}">${label}</a>`).join("")}<a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a></div>
      </div>
    </footer>`;
  document.addEventListener("pointermove", event => {
    const x = Math.round((event.clientX / Math.max(window.innerWidth, 1)) * 100);
    const y = Math.round((event.clientY / Math.max(window.innerHeight, 1)) * 100);
    document.documentElement.style.setProperty("--cursor-x", `${x}%`);
    document.documentElement.style.setProperty("--cursor-y", `${y}%`);
  }, { passive: true });
  const revealItems = document.querySelectorAll(".card:not(.portfolio-card), .split, .app-hero-layout, .scroll-reveal");
  revealItems.forEach((item, index) => {
    item.classList.add("reveal");
    item.style.setProperty("--delay", `${Math.min(index * 45, 360)}ms`);
  });
  const stagedItems = document.querySelectorAll(".story-stage, .app-stage, .hero-title, .bio-card, .contact-panel, .fly-in");
  if ("IntersectionObserver" in window) {
    const observer = new IntersectionObserver(entries => {
      entries.forEach(entry => {
        if (entry.isIntersecting) entry.target.classList.add("is-visible");
      });
    }, { threshold: 0.26, rootMargin: "0px 0px -12% 0px" });
    stagedItems.forEach(item => observer.observe(item));
  } else {
    stagedItems.forEach(item => item.classList.add("is-visible"));
  }
  const heroVideo = document.querySelector(".hero-media");
  if (heroVideo) {
    const startVideo = () => heroVideo.play().catch(() => {});
    if (heroVideo.readyState > 0) startVideo();
    heroVideo.addEventListener("canplay", startVideo, { once: true });
    window.addEventListener("pointerdown", startVideo, { once: true, passive: true });
    window.addEventListener("scroll", startVideo, { once: true, passive: true });
  }
  const sceneVideos = document.querySelectorAll(".forest-media");
  sceneVideos.forEach(video => {
    const startVideo = () => video.play().catch(() => {});
    if (video.readyState > 0) startVideo();
    video.addEventListener("canplay", startVideo, { once: true });
  });
  const updateScrollScenes = () => {
    document.body.classList.toggle("is-scrolled", window.scrollY > 32);
    document.querySelectorAll(".forest-scene").forEach(section => {
      const rect = section.getBoundingClientRect();
      const progress = Math.min(Math.max((window.innerHeight - rect.top) / (window.innerHeight + rect.height), 0), 1);
      section.style.setProperty("--forest-progress", progress.toFixed(4));
    });
  };
  updateScrollScenes();
  window.addEventListener("scroll", updateScrollScenes, { passive: true });
  window.addEventListener("resize", updateScrollScenes, { passive: true });
}

function home() {
  const featured = apps;
  shell("Bamboo Holdings", "Home", `
    <section id="top" class="forest-scene forest-intro">
      <video class="forest-media" autoplay muted loop playsinline poster="${assetUrl("/assets/brand/bamboo-forest-poster.jpg")}" aria-hidden="true">
        <source src="${assetUrl("/assets/brand/bamboo-forest-hero.mp4")}" type="video/mp4">
      </video>
      <div class="forest-shade" aria-hidden="true"></div>
      <a class="scroll-cue" href="${pageUrl("#bio")}" aria-label="Scroll to bio"><span></span></a>
    </section>
    <section id="bio" class="bio-reveal">
      <div class="inner bio-card">
        <div class="bio-copy">
          <p class="eyebrow">Matthew Grossman</p>
          <p class="bio-lede">Matthew co-founded Dorm Room Movers while at Arizona State University and helped grow it from a garage startup into a nationwide logistics operation serving more than 300 colleges, universities, and boarding schools.</p>
          <p>Bamboo is where he works on what comes next: practical software, useful tools, and ideas worth testing.</p>
          <div class="bio-facts" aria-label="Selected background">
            <span><strong>2007</strong> Founded Dorm Room Movers</span>
            <span><strong>300+</strong> Campuses served</span>
            <span><strong>42</strong> States in the network</span>
          </div>
        </div>
        <div class="bio-photo">
          <img src="${assetUrl("/assets/brand/matthew-grossman-headshot.jpg")}" alt="Matthew Grossman" onerror="this.parentElement.classList.add('missing-photo'); this.remove();">
        </div>
      </div>
    </section>
    <section id="apps" class="apps-reveal">
      <div class="apps-wrap">
        <div class="inner app-stage">
          <div class="apps-heading">
            <p class="eyebrow">Current work</p>
            <h2>Current apps</h2>
          </div>
          <div class="app-grid">
            ${featured.map((app, index) => portfolioCard(app, index)).join("")}
          </div>
        </div>
      </div>
    </section>
    <section id="contact" class="forest-scene contact-forest">
      <video class="forest-media" autoplay muted loop playsinline poster="${assetUrl("/assets/brand/bamboo-forest-poster.jpg")}" aria-hidden="true">
        <source src="${assetUrl("/assets/brand/bamboo-forest-hero.mp4")}" type="video/mp4">
      </video>
      <div class="forest-shade contact-shade" aria-hidden="true"></div>
      <div class="inner contact-panel">
        <p class="eyebrow">Contact</p>
        <p>Send a note. No form, no funnel.</p>
        <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>
      </div>
    </section>`);
}

function portfolioCard(app, index = 0) {
  const directions = ["from-left", "from-bottom", "from-right"];
  return `<article class="card portfolio-card app-card-${esc(app.id)} fly-in ${directions[index % directions.length]}" style="--delay: ${index * 140}ms">
    <div class="app-card-top">
      ${appIcon(app)}
      <span class="status">${esc(app.status)}</span>
    </div>
    <h3>${esc(app.name)}</h3>
    <p>${esc(app.tagline)}</p>
    <p>${esc(app.intro)}</p>
    ${app.appStoreUrl ? appStoreBadge(app.appStoreUrl) : `<span class="testflight-badge">TestFlight</span>`}
    <div class="mini-links">
      <a href="${pageUrl(app.slug)}">Overview</a>
      <a href="${pageUrl(`${app.slug}support/`)}">Support</a>
      <a href="${pageUrl(`${app.slug}privacy/`)}">Privacy</a>
    </div>
  </article>`;
}


function appPage(app) {
  shell(`${app.name} - Bamboo Holdings`, "Apps", `
    <section class="app-hero">
      <div class="inner app-hero-layout">
        <div>
          <p class="eyebrow">${esc(app.name)}</p>
          <span class="status">${esc(app.status)}</span>
          <h1>${esc(app.hero)}</h1>
          <p class="lede">${esc(app.intro)}</p>
          <p class="copy">${esc(app.long)}</p>
          <div class="actions">${app.appStoreUrl ? appStoreBadge(app.appStoreUrl) : ""}<a class="button${app.appStoreUrl ? " secondary" : ""}" href="${pageUrl(`${app.slug}support/`)}">Support</a><a class="button secondary" href="${pageUrl(`${app.slug}privacy/`)}">Privacy</a></div>
        </div>
        <div class="product-panel">
          ${appIcon(app)}
          <div class="product-screen">
            ${app.features.slice(0, 4).map(([title, body]) => `<div class="screen-row"><strong>${esc(title)}</strong><span>${esc(body).slice(0, 72)}${body.length > 72 ? "..." : ""}</span></div>`).join("")}
          </div>
          <p class="copy">${esc(app.availability)}</p>
        </div>
      </div>
    </section>
    <section class="inner section">
      <div class="split"><div><p class="eyebrow">Who it is for</p><h2>${esc(app.tagline)}</h2></div><div>${list(app.users)}</div></div>
    </section>
    <section class="band section"><div class="inner"><p class="eyebrow">Key features</p>${cards(app.features)}</div></section>
    <section class="inner section">
      <div class="split"><div><p class="eyebrow">How it works</p><h2>A simple flow from setup to useful output.</h2></div><div>${list(app.works)}</div></div>
    </section>
    <section class="inner section tight"><div class="notice"><strong>Status:</strong> ${esc(app.availability)}<br><strong>Responsible note:</strong> ${esc(app.disclaimer)}</div></section>`);
}

function supportPage(app) {
  shell(`${app.name} Support - Bamboo Holdings`, "Apps", `
    <section class="inner hero narrow">
      <p class="eyebrow">${esc(app.name)} support</p>
      <h1>Support for ${esc(app.name)}</h1>
      <p class="lede">${esc(app.support.overview)}</p>
      <p class="copy">For help, contact <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>.</p>
      <div class="actions"><a class="button secondary" href="${pageUrl(app.slug)}">Back to ${esc(app.name)}</a><a class="button secondary" href="${pageUrl(`${app.slug}privacy/`)}">Privacy</a></div>
    </section>
    <section class="inner section tight prose">
      <h2>When contacting support</h2>
      ${list(app.support.include)}
      ${app.support.caution ? `<p class="notice">${esc(app.support.caution)}</p>` : ""}
      <h2>FAQ</h2>
      ${app.support.faq.map(([q, a]) => `<h3>${esc(q)}</h3><p>${esc(a)}</p>`).join("")}
      <h2>Known limitations</h2>
      ${list(app.support.limitations)}
    </section>`);
}

function privacyPage(app) {
  shell(`${app.name} Privacy - Bamboo Holdings`, "Apps", `
    <section class="inner hero narrow">
      <p class="eyebrow">${esc(app.name)} privacy</p>
      <h1>Privacy overview for ${esc(app.name)}</h1>
      <p class="lede">Effective date: ${TODAY}. This page uses cautious public-safe language from the current reference packet and should be reviewed before public launch.</p>
      <div class="actions"><a class="button secondary" href="${pageUrl(app.slug)}">Back to ${esc(app.name)}</a><a class="button secondary" href="${pageUrl(`${app.slug}support/`)}">Support</a></div>
    </section>
    <section class="inner section tight prose">
      <h2>Data stored</h2>
      ${list(app.privacy.stored)}
      <h2>Data processed locally</h2>
      <p>${esc(app.privacy.local)}</p>
      <h2>Data processed by third parties</h2>
      <p>${esc(app.privacy.thirdParty)}</p>
      <h2>Account/auth status</h2>
      <p>${esc(app.privacy.accounts)}</p>
      <h2>AI processing status</h2>
      <p>${esc(app.privacy.ai)}</p>
      <h2>Children/minors note</h2>
      <p>${esc(app.privacy.children)}</p>
      <h2>Payments note</h2>
      <p>${esc(app.privacy.payments)}</p>
      <h2>Analytics/tracking note</h2>
      <p>${esc(app.privacy.tracking)}</p>
      <h2>Data deletion note</h2>
      <p>${esc(app.privacy.deletion)}</p>
      <h2>Contact</h2>
      <p>Questions can be sent to <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>.</p>
    </section>`);
}



function currentRoutePath() {
  let path = window.location.pathname;
  if (isFilePreview) {
    const rootPath = siteRootUrl.pathname;
    if (path.startsWith(rootPath)) path = path.slice(rootPath.length);
    path = path.replace(/^\/+/, "");
    if (!path || path === "index.html") return "/";
    path = path.replace(/index\.html$/, "");
    return `/${path.replace(/^\/+/, "")}`.replace(/\/?$/, "/");
  }
  return path.endsWith("/") ? path : `${path}/`;
}

function route() {
  const path = currentRoutePath();
  if (path === "/") return home();
  if (path === "/apps/" || path === "/about/" || path === "/contact/") return home();
  const app = apps.find(item => path === item.slug || path === `${item.slug}support/` || path === `${item.slug}privacy/`);
  if (!app) return shell("Page Not Found - Bamboo Holdings", "", `<section class="inner hero narrow"><h1>Page not found.</h1><p class="lede">Return to <a href="${pageUrl("/")}">Bamboo Holdings</a>.</p></section>`);
  if (path.endsWith("/support/")) return supportPage(app);
  if (path.endsWith("/privacy/")) return privacyPage(app);
  return appPage(app);
}

route();
